---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    yum:
      name: 
        - "{{ httpd_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"
